title: "Operating Systems 2021-1 (OS211)"
copyright: "2021-2021"

author: "FXDROS"
address: "Tangsel"
sitemap: "true"

urlweb: "https://FXDROS.github.io/os211/"
urlgithub: "https://github.com/FXDROS/os211/"
urlghpage: "https://FXDROS.github.io/os211/"
github: [metadata]
